version: '3.8'

services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    container_name: escola-api
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual no diretório /app do contêiner
    # Isso permite o live-reloading do código e a persistência do banco de dados SQLite
    volumes:
      - ./:/app